apiVersion: apps/v1
kind: Deployment
metadata:
  name: ProductMgmt
  labels:
    app: ProductMgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ProductMgmt
  template:
    metadata:
      labels:
        app: ProductMgmt
    spec:
      containers:
        - name: ProductMgmt
          image: username/ProductMgmt:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5